name: Test clone

on:
  workflow_dispatch: 
  
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: ls
      run: ls -ltrh
    - name: branchname
      run: echo ${{ github.ref_name }}
    - name: merge if main
      if: github.ref_name == 'main'
      run: echo "Main branch - do not merge"
    - name: merge if not main
      if: github.ref_name != 'main'
      run: | 
         git config --global user.email "you@example.com"
         git config --global user.name "Your Name"
         git fetch --all
         git merge  origin/main -m "test/merge"
    - name: ls again
      run: ls -ltrh
      
